apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v8
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v8
    kubernetes.io/cluster-service: "true"
spec:
  {% if dns_replicas -%}replicas: {{ dns_replicas }} {% else %}replicas: 1 {% endif %}
  selector:
    k8s-app: kube-dns
    version: v8
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v8
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.11
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/kube2sky"
        {% if dns_domain -%}- -domain={{ dns_domain }}. {% else %}- -domain=cluster.local. {% endif %}
        - -kube_master_url=http://{{ private_address }}:8080
        - --etcd-server={{ connection_string }}
      - name: skydns
        image: gcr.io/google_containers/skydns:2015-03-11-001
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/skydns"
        {% if dns_domain -%}- -domain={{ dns_domain }}. {% else %}- -domain=cluster.local. {% endif %}
        - -machines={{ connection_string }}
        - -addr=0.0.0.0:53
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
      - name: healthz
        image: gcr.io/google_containers/exechealthz:1.0
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
        args:
        {% if dns_domain -%}- -cmd=nslookup kubernetes.default.svc.{{ dns_domain }} localhost >/dev/null {% else %}- -cmd=nslookup kubernetes.default.svc.cluster.local localhost >/dev/null {% endif %}
        - -port=8080
        ports:
        - containerPort: 8080
          protocol: TCP
      volumes:
      - name: etcd-storage
        emptyDir: {}
      dnsPolicy: Default  # Don't use cluster DNS.
